AllCops:
  Exclude:
    - config.ru
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

LineLength:
  Max: 130
  Exclude:
    - config/environments/*
    - config/initializers/backtrace_silencers.rb
    - db/seeds.rb
    - db/seeds/project_seeder.rb

YAMLLoad:
  Exclude:
    - bin/webpack
    - bin/webpack-dev-server
