default: &default
  adapter: postgresql
  database: <%= Rails.application.secrets.database %>
  encoding: unicode
  password: <%= Rails.application.secrets.postgres_password %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.secrets.postgres_user %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: <%= Rails.application.secrets.host %>
  port: <%= Rails.application.secrets.port %>
