# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  database: jprince_codes_development
  postgres_password: pgpass
  postgres_user: pguser
  secret_key_base: 704d2bdc7e569c7cd7a727e86268aca4c480357ae22ec1178375e7e010c22985c96f2437a624f5aca8ee29ab5f8b0e8e68c633110873a721da71ca4e637f742e

test:
  database: jprince_codes_test
  postgres_password: pgpass
  postgres_user: pguser
  secret_key_base: f02d4f32c634ad30c6b3ef107346aebad11d5ec64cfa3ed7daddd1471c1330417406a3c9c51a47149bd986ed2c41cddff604212885ded3e266721d13ae347ea4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  database: <%= ENV['RDS_DB_NAME'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  postgres_password: <%= ENV['RDS_PASSWORD'] %>
  postgres_user: <%= ENV['RDS_USERNAME'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
